### ISSUE TITLE
Building without sudo

### ISSUE THREAD

**Issue by TheDan64** [codecov/example-rust#6]
Hi, is there any way to get this to work without sudo? Travis seems to be making a big push to get people to not use sudo anymore.

**Comment by sunjay** [comment]
Yes I believe there should be. The only uses I see of sudo are in before install and when installing kcov. I don't believe either of these are truly necessary. Could you try removing the before install all together and removing sudo from the other instance and see what happens?

**Comment by TheDan64** [comment]
It's the `sudo make install` part that doesn't seem to work without sudo:

```bash
-- Installing: /usr/local/bin/kcov

CMake Error at src/cmake_install.cmake:42 (FILE):

  file INSTALL cannot copy file

  "/home/travis/build/TheDan64/inkwell/kcov-master/build/src/kcov" to

  "/usr/local/bin/kcov".

Call Stack (most recent call first):

  cmake_install.cmake:37 (INCLUDE)

make: *** [install] Error 1
```

I guess it's trying to copy to the /usr/ directory for some reason

**Comment by sunjay** [comment]
Yes that is the problem.

Could you try this configuration?

```yml
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/examplerust-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
```

Appreciate you debugging this with me. :smile:

**Comment by sunjay** [comment]
Another option is to use something like [cargo-travis](https://github.com/roblabla/cargo-travis) instead of all of this. They explicitly use `sudo: false` in [their configuration](https://github.com/roblabla/cargo-travis#example).

**Comment by TheDan64** [comment]
That errored with:
```
-- Installing: ../../kcov/usr/local/bin/kcov
-- Removed runtime path from "../../kcov/usr/local/bin/kcov"
-- Installing: ../../kcov/usr/local/share/man/man1/kcov.1
/home/travis/.travis/job_stages: line 67: ./kcov: Is a directory
```

**Comment by sunjay** [comment]
Thanks for trying it out! Sorry about that. That is my mistake. I accidentally tried to build the `kcov` executable to the same place as where the `kcov` directory was cloned from GitHub. :sweat_smile: 

I modified the code below to produce an executable named `kcov-build` instead.

Please try this:

```yml
language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/examplerust-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
```
